<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DisableGitVersioning>true</DisableGitVersioning>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSourceRevisionInPackageVersion>false</IncludeSourceRevisionInPackageVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableGitVersioning>false</EnableGitVersioning>
    <DeterministicSourcePaths>false</DeterministicSourcePaths>
    <PackageId>Hyz.HttpClient</PackageId>
    <Version>0.1.9</Version>
	<Authors>hyz</Authors>
	<PackageId>$(AssemblyName)</PackageId>
	<Title>$(AssemblyName)</Title>
    <Description>优雅的HttpClient封装，目标框架是 netstandard2.0 ，兼容 .NET Framework 4.6.1+ 和 .NET Core 2.0+，支持多种HTTP方法、重试机制、熔断保护、请求头管理等特性</Description>
    <PackageTags>HttpClient;REST;API;HTTP;Polly;Retry;CircuitBreaker;GET;POST;PUT;DELETE;PATCH</PackageTags>
    <RepositoryUrl>https://github.com/zenghongyao/Hyz.HttpClient.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>支持GET/POST/PUT/DELETE/PATCH方法、重试机制、熔断保护、请求头管理、查询参数、请求体、参数别名、小驼峰命名、请求拦截器、证书配置、JSON反序列化等特性</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
    <PackageReference Include="Polly" Version="8.4.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.6" />
  </ItemGroup>
	
	<!-- 引入 README.md -->
	<ItemGroup>
		<None Include="../../README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
